# Generated by Django 5.0.1 on 2025-11-15 05:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='사용 가능 재화')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='입찰 중이거나 사용 대기 중인 재화', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='잠금 재화')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='총 획득 재화')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='총 사용 재화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '재화',
                'verbose_name_plural': '재화 목록',
                'db_table': 'currencies',
                'indexes': [models.Index(fields=['user'], name='currencies_user_id_acf45e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='양수: 증가, 음수: 감소', max_digits=15, verbose_name='금액')),
                ('transaction_type', models.CharField(choices=[('EARN', '획득'), ('CHARGE', '충전'), ('BID', '입찰'), ('BID_CANCEL', '입찰 취소'), ('WIN', '낙찰'), ('LOSE', '낙찰 실패'), ('REFUND', '환불'), ('FEE', '수수료'), ('RECEIVE', '판매 대금 수령'), ('LOCK', '재화 잠금'), ('UNLOCK', '재화 잠금 해제')], max_length=20, verbose_name='거래 유형')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 전 잔액')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 후 잔액')),
                ('locked_balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='거래 전 잠금 재화')),
                ('locked_balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='거래 후 잠금 재화')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('reference_id', models.CharField(blank=True, help_text='관련 경매 ID, 주문 ID 등', max_length=100, verbose_name='참조 ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '재화 거래 내역',
                'verbose_name_plural': '재화 거래 내역 목록',
                'db_table': 'currency_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='currency_tr_user_id_8af6b3_idx'), models.Index(fields=['transaction_type'], name='currency_tr_transac_d1b2d9_idx'), models.Index(fields=['reference_id'], name='currency_tr_referen_c06645_idx')],
            },
        ),
    ]
